function [data, auxData, metaData, txtData, weights] = mydata_Salmo_marmoratus
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Chordata';
metaData.class      = 'Actinopterygii';
metaData.order      = 'Salmoniformes';
metaData.family     = 'Salmonidae';
metaData.species    = 'Salmo_marmoratus';
metaData.species_en = 'Marbled trout';

metaData.ecoCode.climate = {'Csa','Csb','Dfb','MB','MC'};
metaData.ecoCode.ecozone = {'THp','MAm'};
metaData.ecoCode.habitat = {'bjF','piFr','piFl','piMcb','piMb'};
metaData.ecoCode.embryo  = {'Fs','Ft','Fnm'};
metaData.ecoCode.migrate = {'Mda'};
metaData.ecoCode.food    = {'piCid','bxCii','piCvf'};
metaData.ecoCode.gender  = {'D'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(8); % K, body temp

metaData.data_0     = {'ab','am','Lb','Lp','Li','Wwi'};
metaData.data_1     = {};

metaData.COMPLETE   = 2; % using criteria of LikaKear2011

metaData.author     = {'Gauthier Clélia'};
metaData.date_subm  = [2021 5 19];
metaData.email      = {'cleliagauthier16@gmail.com'};
metaData.address    = {'INRAE, Saint-Pée-sur-Nivelle'};

metaData.curator    = {'Starrlight Augustine'};
metaData.email_cur  = {'starrlight.augustine@akvaplan.niva.no'};
metaData.date_acc   = [2021 5 19];

%% set zero-variate data
data.ab = 90; units.ab = 'd'; label.ab = 'age at birth'; bibkey.ab = {'VincCriv2007'};
  temp.ab = C2K(8); units.temp.ab = 'K'; label.temp.ab = 'temperature';
data.am = 2190; units.am = 'd'; label.am = 'life span'; bibkey.am = {'VincCriv2007'};
  temp.am = C2K(8); units.temp.am = 'K'; label.temp.am = 'temperature';

data.Lb = 8; units.Lb = 'cm'; label.Lb = 'length at birth'; bibkey.Lb = {'CrivPoiz2000'};
data.Lp = 20; units.Lp = 'cm'; label.Lp = 'length at puberty'; bibkey.Lp = {'VincCri2007'};
data.Li = 40; units.Li = 'cm'; label.Li = 'ultimate length'; bibkey.Li = {'VincCri2007'};

data.Wwi = 590; units.Wwi = 'g'; label.Wwi = 'ultimate wet weight'; bibkey.Wwi = {'VincCriv2007'};

%% set weights for all real data
weights = setweights(data, []);

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;

%% Links
metaData.links.id_CoL = '79CYT'; % Cat of Life
metaData.links.id_EoL = '1157691'; % Ency of Life
metaData.links.id_Wiki = 'Salmo_marmoratus'; % Wikipedia
metaData.links.id_ADW = 'Salmo_marmoratus'; % Anim Div. Web
metaData.links.id_Taxo = '186420'; % Taxonomicon
metaData.links.id_WoRMS = '1019650';
metaData.links.id_fishbase = 'Salmo-marmoratus';

%% References
bibkey = 'CrivPoiz2000'; type = 'article'; bib = [ ...
'author = {Crivelli}, ' ... 
'title = {Conservation biology applied to fish: the example of a project for rehabilitating the marble trout (Salmo marmoratus) in Slovenia}, ' ... 
'journal = {Cybium}, ' ... 
'year = {2000}, ' ... 
'volume = {24}, ' ... 
'pages = {211-230}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'VincCri2007'; type = 'article'; bib = [ ...
'author = {Vincenzi}, ' ... 
'title = {Density-dependent individual growth of marble trout (Salmo marmoratus) in the Soca and Idrijca river basins, Slovenia}, ' ... 
'journal = {Hydrobiologia}, ' ... 
'year = {2007}, ' ... 
'volume = {583}, ' ... 
'pages = {57-68}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'VincCriv2007'; type = 'article'; bib = [ ...
'author = {Vincenzi}, ' ... 
'title = {Early survival of marble trout Salmo marmoratus: evidence for density dependence?}, ' ... 
'journal = {Ecology of Freshwater Fish}, ' ... 
'year = {2007}, ' ... 
'volume = {16}, ' ... 
'pages = {116-123}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
